name: samar_tech_pro
description: تطبيق إدارة RouterOS
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  routeros_api: ^2.1.0
  pdf: ^3.10.0
  printing: ^5.12.0

flutter:
  uses-material-design: true
